version: "3"
services:
  python:
    image: brian978/django-py:3.7
    links:
      - mysql
    ports:
      - "8383:8000"
    volumes:
      - ./app:/usr/src/app

  mysql:
    image: mysql:5.6
    ports:
      - "33061:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    volumes:
      - mssql-volume:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SomePwd123456

volumes:
    mysql-volume:
    mssql-volume:
