version: "3"
services:
  python:
    image: brian978/django-py:3.7
    links:
      - db
    ports:
      - "8383:8000"
    volumes:
      - ./app:/usr/src/app

  db:
    image: mysql:5.6
    ports:
      - "33061:3306"
    volumes:
      - ./persistent/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
